# @package _global_
loss:
    _target_: losses.clDice_loss.soft_dice_cldice
    iter_: 20
    alpha: 0.5
    smooth: 1.0
    exclude_background: False
    ignore_index: ${dataset.ignore_index}
    is_binary: True